name: Build and testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_routes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Test routes
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          DBL_TOKEN: ${{ secrets.DBL_TOKEN }}
        run: yarn test
      - name: Run build
        run: yarn build
